### ISSUE TITLE
SkriptLoader instances, less static

### ISSUE THREAD

**Issue by Trigary** [stefvanschie/QuickSkript#11]
Currently, the `static` modifier is used even in singleton factory instances (for the `Pattern`s). This makes it nearly impossible to later get rid of all these unnecessary variables. Why would we want to get rid of them, why are they unnecessary? All Skript plugins are loaded at startup, there is no need to keep all of the factory instances in memory after the loading is done.

These singleton (but partially `static`) factories are collected in `static` utility classes. Instead of this, I propose to make a `SkriptLoader` instance which would hold the factory instances, instead of having them as `static`. `SkriptLoader` instances might even offer easier expandability if Skript libraries are to become supported. They could also be cached or re-created for whatever reason (eg. loading more Skripts after the initial startup) - allowing more flexibility for both QuickSkript and other plugins dependent on QuickSkript.

In case this proposal gets a green light, I will gladly get this done. I would just rather get a response before spending time making these changes.

**Comment by stefvanschie** [comment]
This definitely sounds useful, so I'll gladly accept any changes regarding this.

**Comment by Trigary** [comment]
Great!
