### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Trigary** [stefvanschie/QuickSkript#16]
A lot more tests should be added: while the codebase has been expanded, the count of tests hasn't increased. These tests should do more than just testing the individual `PsiElement`s, but tests for those would also come in handy if someone has the patience to write them.

Addition of the [Mockito](https://search.maven.org/artifact/org.mockito/mockito-core/2.21.0/jar) framework should be considered.

**Comment by stefvanschie** [comment]
I agree more tests are needed (since we only have one currently). I'm not too familiar with writing tests myself, but if needed I'd be willing to do a bit of research and write them.

I've never worked with Mockito before, but it looks good, so I could add that if wanted.

**Comment by Trigary** [comment]
At the moment I have run out of ideas (see #18). I am closing this issue and will try to add tests when new features are added / get inspiration to do so.
