### ISSUE TITLE
Including relevant information in parse/execution errors

### ISSUE THREAD

**Issue by Trigary** [stefvanschie/QuickSkript#17]
Currently, only the actual cause of the exceptions and their source file are logged. This may not help all that much when trying to debug the issue. More relevant information, eg. the file section / line number or the event / command name should be considered to be included.

**Comment by stefvanschie** [comment]
We could add a line number to the SkriptFileNode which we can retrieve when loading the file. Then we can give each PsiElement a line number based on the SkriptFileNode being parsed. Whenever we throw an error from a PsiElement, we can include the line number (probably add another constructor to the desired Exceptions to include the line number (we can also replace the current one if that's more desirable)), so the underlying catch statement can use that to print a useful error message. We can also add the command/event the line is in for `ExecutionException`s, seeing as the catching of those already happens inside the SkriptEvent and SkriptCommand classes.

I'd be up for making this if needed.

**Comment by Trigary** [comment]
I will try to work on tests then.

**Comment by stefvanschie** [comment]
Alright, that'd be great, thanks.

**Comment by stefvanschie** [comment]
I've implemented line numbers in the system and errors will now show the line number as well.
