### ISSUE TITLE
Don't shade the JetBrains annotations for Bukkit

### ISSUE THREAD

**Issue by Trigary** [stefvanschie/QuickSkript#30]
There are two reasons for this:
 - they are available at runtime (Bukkit/Spigot/Whatever shades them in)
 - we are not using any of their runtime features

Is shading them into `core` necessary? Maybe, I don't know.

**Comment by stefvanschie** [comment]
The runtime assertions seem to be generated by the IDE and don't require the actual JAR file to be shaded, so I have changed the scope from shade to provided to prevent the inclusion of them.

**Comment by Trigary** [comment]
I think a relocation still exists which only affected this dependency:
```
<relocation>
	<pattern>org.jetbrains</pattern>
	<shadedPattern>${package}.shaded.org.jetbrains</shadedPattern>
</relocation>
```
